chore: switch architecture

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -168,11 +168,21 @@ jobs:
           url="https://github.com/x71c9/tempesta"
           license=('MIT')
           depends=('glibc')
-          source=(
-            "https://github.com/x71c9/tempesta/releases/download/v${version}/tempesta-x86_64-unknown-linux-gnu.tar.gz"
-            "https://github.com/x71c9/tempesta/releases/download/v${version}/tempesta-aarch64-unknown-linux-gnu.tar.gz"
-          )
-          sha256sums=('SKIP' 'SKIP')
+
+          case "\$arch" in
+            "x86_64")
+              source=("https://github.com/x71c9/tempesta/releases/download/v${version}/tempesta-x86_64-unknown-linux-gnu.tar.gz")
+              sha256sums=('SKIP')
+              ;;
+            "aarch64")
+              source=("https://github.com/x71c9/tempesta/releases/download/v${version}/tempesta-aarch64-unknown-linux-gnu.tar.gz")
+              sha256sums=('SKIP')
+              ;;
+            *)
+        echo "Error: Unsupported architecture \$arch. Please open a github issue if you want to support it: https://github.com/x71c9/tempesta/issues" >&2
+              exit 1
+              ;;
+          esac
 
           package() {
             install -Dm755 "\${srcdir}/tempesta" "\${pkgdir}/usr/bin/tempesta"
