chore: indentation

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -179,7 +179,7 @@ jobs:
               sha256sums=('SKIP')
               ;;
             *)
-        echo "Error: Unsupported architecture \$arch. Please open a github issue if you want to support it: https://github.com/x71c9/tempesta/issues" >&2
+              echo "Error: Unsupported architecture \$arch. Please open a github issue if you want to support it: https://github.com/x71c9/tempesta/issues" >&2
               exit 1
               ;;
           esac
